services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/nextstep.db
      - JwtSettings__SecretKey=${JWT_SECRET_KEY:-MineSuperSecretKeyThatIsAtLeast32CharactersLong!}
      - AppSettings__BaseUrl=${BACKEND_BASE_URL:-http://backend:7010}
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M

  frontend:
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL:-http://backend:7010}
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
