services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nextstep-backend
    ports:
      - "7010:7010"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7010
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/nextstep.db
    volumes:
      # Persist SQLite database
      - backend_data:/app/data
    networks:
      - nextstep-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextstep-frontend
    ports:
      - "8080:8080"
    environment:
      - VITE_BACKEND_URL=http://backend:7010
    depends_on:
      - backend
    networks:
      - nextstep-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backend_data:
    driver: local

networks:
  nextstep-network:
    driver: bridge
